minimal_mistakes_skin: default
locale: en-US
title: Ugur Elveren
title_separator: '-'
name: null
description: 'Another boring blog!'
url: null
baseurl: null
repository: null
teaser: null
logo: null
masthead_title: null
words_per_minute: 200
comments:
  provider: null
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
  utterances:
    theme: null
    issue_term: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
  endpoint: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
search: null
search_full_content: null
search_provider: null
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: false
  google:
    tracking_id: null
    anonymize_ip: null
author:
  name: null
  avatar: "/assets/images/pf.jpg"
  bio: 'Another boring blog!'
  location: 'Huntington Beach, CA.'
  email: null
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
    - label: Website
      icon: fas fa-fw fa-link
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
    - label: GitHub
      icon: fab fa-fw fa-github
      url: "https://github.com/ugurelveren"
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: "https://www.instagram.com/ugur.elveren/"
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: "https://www.linkedin.com/in/ugur-elveren/"
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
    - label: GitHub
      icon: fab fa-fw fa-github
      url: "https://github.com/ugurelveren"
    - label: GitLab
      icon: fab fa-fw fa-gitlab
    - label: Bitbucket
      icon: fab fa-fw fa-bitbucket
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: ""
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: null
      share: true
      related: true
